version: "3.5"
services:
  couga54-nginx:
    build:
      context: ..
      dockerfile: docker/${Dockerfile}
    image: ${DockerRegistry}/${ImageName}:${ImageTag}
    container_name: ${ImageName}
    ports: 
      - "80:80"
    restart: always
