name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Test env parameters
        run: 
#           echo couga54/exam:0.0.1-b${{ github.run_number }}
          echo $(ImageTag) from .env file
#       - name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: app
#           push: true
#           tags: couga54/exam:0.0.1-b${{ github.run_number }}

      - name: Build and push docker-compose
        run: cd docker 
             docker-compose -f docker-compose-exam.yml build 
   
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
